# File variables
@baseUrl = https://httpbin.org
@token = demo

###
# Basic GET with query params
GET {{baseUrl}}/get?foo=bar&limit=3
Accept: application/json

###
# Custom headers
GET {{baseUrl}}/anything/headers
Accept: application/json
X-Test-Header: ReqRun-Test
X-Request-Id: {{$uuid}}
User-Agent: ReqRun/1.0

###
# Blank lines between request line and headers
POST {{baseUrl}}/post

Accept: application/json
Content-Type: application/json

{
  "message": "Hello from ReqRun",
  "count": 3,
  "token": "{{token}}"
}

###
# Comment separator between headers and body
POST https://countries.trevorblades.com/
Accept: application/json
Content-Type: application/json
# Body starts below
{
  "query": "query { countries { code name emoji } }"
}

###
# Form URL encoded
POST https://postman-echo.com/post
Accept: application/json
Content-Type: application/x-www-form-urlencoded

foo=bar&number=42

###
# PUT with JSON body
PUT {{baseUrl}}/put
Accept: application/json
Content-Type: application/json

{"update": true}

###
# DELETE
DELETE {{baseUrl}}/delete
Accept: application/json

###
# HEAD
HEAD {{baseUrl}}/get
Accept: application/json

###
# XML body
POST {{baseUrl}}/post
Accept: application/json
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <ping>ReqRun</ping>
  </soapenv:Body>
</soapenv:Envelope>

###
# Multipart form-data with file
POST {{baseUrl}}/post
Accept: application/json
Content-Type: multipart/form-data; boundary=ReqRunBoundary

--ReqRunBoundary
Content-Disposition: form-data; name="title"

ReqRun Multipart
--ReqRunBoundary
Content-Disposition: form-data; name="file"; filename="note.txt"
Content-Type: text/plain

< ./note.txt
--ReqRunBoundary--

###
# Multipart form-data without files
POST {{baseUrl}}/post
Accept: application/json
Content-Type: multipart/form-data; boundary=ReqRunBoundary

--ReqRunBoundary
Content-Disposition: form-data; name="title"

ReqRun Fields
--ReqRunBoundary
Content-Disposition: form-data; name="count"

3
--ReqRunBoundary--

###
# Raw body
POST {{baseUrl}}/post
Accept: application/json
Content-Type: application/octet-stream

Raw binary bytes: 00 01 02 03 04

###
# Streaming response
GET {{baseUrl}}/stream/5
Accept: application/x-ndjson

###
# Save response to file
GET {{baseUrl}}/image/png
Accept: image/png
> ./downloads/image.png
