# Basic GET with query params
GET https://httpbin.org/get?foo=bar&limit=3
Accept: application/json

###
# Custom headers
GET https://httpbin.org/anything/headers
Accept: application/json
X-Test-Header: ReqRun-Test
User-Agent: ReqRun/1.0

###
# Blank lines between request line and headers
POST https://httpbin.org/post

Accept: application/json
Content-Type: application/json

{
  "message": "Hello from ReqRun",
  "count": 3
}

###
# Comment separator between headers and body
POST https://countries.trevorblades.com/
Accept: application/json
Content-Type: application/json
# Body starts below
{
  "query": "query { countries { code name emoji } }"
}

###
# Form URL encoded
POST https://postman-echo.com/post
Accept: application/json
Content-Type: application/x-www-form-urlencoded

foo=bar&number=42

###
# PUT with JSON body
PUT https://httpbin.org/put
Accept: application/json
Content-Type: application/json

{"update": true}

###
# DELETE
DELETE https://httpbin.org/delete
Accept: application/json

###
# HEAD
HEAD https://httpbin.org/get
Accept: application/json

###
# XML body
POST https://httpbin.org/post
Accept: application/json
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
  <soapenv:Body>
    <ping>ReqRun</ping>
  </soapenv:Body>
</soapenv:Envelope>

###
# Multipart form-data
POST https://httpbin.org/post
Accept: application/json
Content-Type: multipart/form-data; boundary=ReqRunBoundary

--ReqRunBoundary
Content-Disposition: form-data; name="title"

ReqRun Multipart
--ReqRunBoundary
Content-Disposition: form-data; name="file"; filename="note.txt"
Content-Type: text/plain

Hello from ReqRun multipart.
--ReqRunBoundary--

###
# Raw body
POST https://httpbin.org/post
Accept: application/json
Content-Type: application/octet-stream

Raw binary bytes: 00 01 02 03 04

###
# Streaming response
GET https://httpbin.org/stream/5
Accept: application/x-ndjson
